services:
  mysql:
    image: mysql:8.0.32
    container_name: user-service-db-ita
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emce142107
      MYSQL_DATABASE: BookManagement
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - user-service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-ita
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-service-db-ita:3306/BookManagement
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - user-service-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  user-service-network:
    driver: bridge