services:
  activemq:
    image: rmohr/activemq:latest
    container_name: user-service-activemq-ita
    ports:
      - "61616:61616"  # JMS port
      - "8161:8161"    # Web Console port
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0.32
    container_name: user-service-db-ita
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emce142107
      MYSQL_DATABASE: BookManagement
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - user-service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-ita
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-service-db-ita:3306/BookManagement
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SERVER_PORT: 8080
      SPRING_ACTIVEMQ_BROKER_URL: tcp://user-service-activemq-ita:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - user-service-network
    depends_on:
      mysql:
        condition: service_healthy
      activemq:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  user-service-network:
    driver: bridge