version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    container_name: transaction-service-db-ita
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emce142107
      MYSQL_DATABASE: Transactions
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - transaction-service-network
      - shared-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction-service-ita:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service-ita
    restart: always
    environment:
      MYSQL_HOST: transaction-service-db-ita
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_DB: Transactions
      ACTIVEMQ_BROKER: shared-activemq
      ACTIVEMQ_BROKER_PORT: 61616
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
      JWT_SECRET: GD01pc7/7BmRWmWtY71dIUjR1G+we3N5d9EKYWmzuFI6o6eRCsetl/9KruFclnFwmb7B9I62hhDfjUAl3IUDUw==
      PORT: 6000
    ports:
      - "6000:6000"
    networks:
      - transaction-service-network
      - shared-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  transaction-service-network:
    driver: bridge
  shared-network:
    external: true