services:
  activemq:
    image: rmohr/activemq:latest
    container_name: transaction-service-activemq-ita
    ports:
      - "61618:61616"  # Different external port
      - "8163:8161"    # Different web console port
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - transaction-service-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0.32
    container_name: transaction-service-db-ita
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emce142107
      MYSQL_DATABASE: Transactions
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3310:3306" # Different port from book-service to avoid conflicts
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - transaction-service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction-service-ita:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service-ita
    restart: always
    environment:
      MYSQL_HOST: transaction-service-db-ita
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_DB: Transactions
      ACTIVEMQ_BROKER_URL: tcp://transaction-service-activemq-ita:61616
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
      - "6000:6000"
    networks:
      - transaction-service-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  transaction-service-network:
    driver: bridge