# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x07\n\x05\x45mpty\"\x14\n\x06\x42ookId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\nBookUserId\x12\x0e\n\x06userId\x18\x01 \x01(\x03\"J\n\x0b\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x0e\n\x06userId\x18\x04 \x01(\x03\"c\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x0e\n\x06userId\x18\x06 \x01(\x03\"%\n\x08\x42ookList\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9d\x02\n\x0b\x42ookService\x12,\n\x0bGetAllBooks\x12\x0b.book.Empty\x1a\x0e.book.BookList\"\x00\x12%\n\x07GetBook\x12\x0c.book.BookId\x1a\n.book.Book\"\x00\x12\x34\n\x0eGetBooksByUser\x12\x10.book.BookUserId\x1a\x0e.book.BookList\"\x00\x12-\n\nCreateBook\x12\x11.book.BookRequest\x1a\n.book.Book\"\x00\x12(\n\nUpdateBook\x12\n.book.Book\x1a\x0c.book.Status\"\x00\x12*\n\nDeleteBook\x12\x0c.book.BookId\x1a\x0c.book.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_BOOKID']._serialized_start=29
  _globals['_BOOKID']._serialized_end=49
  _globals['_BOOKUSERID']._serialized_start=51
  _globals['_BOOKUSERID']._serialized_end=79
  _globals['_BOOKREQUEST']._serialized_start=81
  _globals['_BOOKREQUEST']._serialized_end=155
  _globals['_BOOK']._serialized_start=157
  _globals['_BOOK']._serialized_end=256
  _globals['_BOOKLIST']._serialized_start=258
  _globals['_BOOKLIST']._serialized_end=295
  _globals['_STATUS']._serialized_start=297
  _globals['_STATUS']._serialized_end=322
  _globals['_BOOKSERVICE']._serialized_start=325
  _globals['_BOOKSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
