version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    container_name: book-service-db-ita
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emce142107
      MYSQL_DATABASE: Books
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - book-service-network
      - shared-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  book-service-ita:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-service-ita
    restart: always
    environment:
      DB_HOST: book-service-db-ita
      DB_USER: springstudent
      DB_PASSWORD: springstudent
      DB_NAME: Books
      PORT: 50051
      ACTIVEMQ_BROKER_URL: tcp://shared-activemq:61616 
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
      - "50051:50051"
    networks:
      - book-service-network
      - shared-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  book-service-network:
    driver: bridge
  shared-network:
    external: true