name: Book Service Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: secrets.MYSQL_PASSWORD
          MYSQL_DATABASE: Books
          MYSQL_USER: springstudent
          MYSQL_PASSWORD: springstudent
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -la

      - name: List services directory contents
        run: ls -la services

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install
        working-directory: services/book-service 

      - name: Run tests
        run: npm test 
        working-directory: services/book-service 
