name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push Book Service image
      - name: Build and push Book Service
        uses: docker/build-push-action@v6
        with:
          context: ./services/book-service
          file: ./services/book-service/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{ github.sha }}

      # Step 5: Build and push Transaction Service image
      - name: Build and push Transaction Service
        uses: docker/build-push-action@v6
        with:
          context: ./services/transaction-service
          file: ./services/transaction-service/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/transaction-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/transaction-service:${{ github.sha }}

      # Step 6: Build and push User Service image
      - name: Build and push User Service
        uses: docker/build-push-action@v6
        with:
          context: ./services/user-service
          file: ./services/user-service/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}

      # Step 7: Build and push Web API Gateway image
      - name: Build and push Web API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./services/web-api-gateway
          file: ./services/web-api-gateway/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web-api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web-api-gateway:${{ github.sha }}
