name: Transaction Service Unit Tests

on:
  push:
    branches:
      - main  
    paths:
      - '**.py' 
      - 'requirements.txt' 
      - '.github/workflows/transaction-service.yml' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Match the Python version used in your Dockerfile

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p 'test_*.py' -v
